docling_core/search/package.py, poetry.lock, pyproject.toml
For consistency, set the default value for name field in search.package.Package to doocling-core, since the field version is set to docling-core version by default.
=> chore: set default name field in Package to docling-core

docling_core/search/json_schema_to_search_mapper.py, docs/Document.json, docs/Document.md, docs/Generic.json, docs/Generic.md, poetry.lock, test/test_json_schema_to_search_mapper.py
- In the JSON Schema to search mapper, the suppression flags need to be addressed first, otherwise the `jsonref.replace_refs` function may remove them.
- Updating pydantic from `2.8.2` to `2.9.2` triggers a change in JSON Schema from models: the  lists with only 1 element get flattened. The documentation is automatically updated.
=> fix: change order of JSON Schema to search mapper transformations

docling_core/transforms/chunker/hierarchical_chunker.py, poetry.lock, pyproject.toml
Change for compatibility with `ibm-watsonx-ai`.
```
pip install ibm-watsonx-ai "pandas>=2.2.2,<3.0.0"
[...]
ERROR [...]
The conflict is caused by:
The user requested pandas<3.0.0 and >=2.2.2
ibm-watsonx-ai 1.1.14 depends on pandas<2.2.0 and >=0.24.2
[...]
```
=> fix: loosen pandas version

docling_core/utils/file.py
Currently, when we use the docling cli, we often can not pull the html pages, because we do not have compliant requests with user-agents. This PR fixes that.
=> feat: add headers argument and a custom user-agents for http requests

docling_core/types/doc/document.py
Our export markdown doesn't contain any emphasis styling: Bold, Italic, or Bold-Italic
Hence, any underscore that we print into Markdown is coming from document text, that means we need to escape it, to properly reflect content in the markdown
=> fix: Escaping underscore characters in md export

docling_core/types/doc/document.py
This changes impact only the case when a backend (or some user manipulation) defined an image with a remote url. It should be perfectly fine to return it in the exported html and markdown.
Refs: https://github.com/DS4SD/docling/discussions/477
=> fix: allow all url types in referenced exports

docling_core/types/doc/document.py
I wrote utility functions in a script to save and load `DoclingDocument` objects to file:
```python
def save_document(document: DoclingDocument, document_json_path: Union[str, Path]):
with open(document_json_path, 'w') as f:
f.write(document.model_dump_json(indent=4))
def load_document(document_json_path: Union[str, Path]) -> DoclingDocument:
assert os.path.exists(document_json_path), f"Document JSON file not found: {document_json_path}"
with open(document_json_path, 'r') as f:
json_data = json.load(f)
return DoclingDocument(**json_data)
```
Which saved a lot of time when testing workflows with very long, complex documents. Not needing to reprocess the documents each time was very useful, but I did not see a builtin tool to save to a file directly (like `pandas.DataFrame.to_csv`), so I …
=> feat: simple method to load DoclingDocument from .json files

docling_core/types/io/__init__.py, docling_core/utils/file.py, poetry.lock, pyproject.toml, test/test_utils.py
Extension to the resolution of file source
1. Add `workdir` to `resolve_file_source()` by keeping it backwards compatible. 
2. Add a new version `read_file_source()` which returns a document stream to completely avoid writing files
This will be used in Docling to avoid having leftover files in the temporary dir.
=> feat: extend source resolution with streams and workdir

docling_core/types/doc/document.py, test/data/doc/constructed_doc.referenced.md.gt, test/test_docling_doc.py
Solved the problem in this issue(#97)
Previously, all underscores in markdown output were escaped to prevent emphasis styling, which broke image URLs containing underscores. This fix modifies the underscore escaping logic to:
- Identify image URL patterns in markdown text
- Skip underscore escaping within image URL sections
- Continue escaping underscores in regular text content
=> fix(markdown): preserve underscores in image URLs during markdown export

docling_core/types/doc/document.py
Using latest docling-core (v2.6.1) and docling (v2.8.1) xlsx files are unable to be processed due to a ValueError mentioning that the mimetype `"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"` is not valid as per DocumentOrigin
`"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"` is not a mimetype offered by default by the `mimetype` pkg being used by docling and hence has to be added in the extras section
Add the mimetype as an extra mimetype
=> Bug: Support XLSX Mimetype

docling_core/types/doc/document.py
- Add references in the exported output
- Remove the code-removal of captions and make it instead explicit via exported set
=> fix: add REFERENCE to exported labels and remove CAPTION

docling_core/types/doc/document.py
Resolves #102 
Change the 'parent' argument type of the functions in DoclingDocument that allow adding text items, to enable all type of parent items instead of only group items.
=> chore: change the 'parent' arg type of DoclingDocument functions

docling_core/types/doc/document.py
Note: export to html and doc_tokens is already taking care of it.
Resolves #112
=> fix: skip labels not included in the allow-list

docling_core/types/doc/labels.py, docs/DoclingDocument.json
To address comments and hidden text, we add a new group:
1. Things like slide comments, Word review comments, etc. should go into the furniture root and be put inside a group with new GroupLabel.COMMENT_SECTION
2. Optional: We can extend the type hierachy with a CommentItem, which additionally stores an author name and timestamp with the text.
3. We must add filter argument for group labels on the export functions (additional to DocItemLabels)
=> feat: added the new label comment_section in the groups

docling_core/transforms/chunker/base.py, docling_core/transforms/chunker/hybrid_chunker.py, pyproject.toml
strict pyright forbids calling this function with missing annotation
=> chore: annotate `**kwargs` in `HybridChunker.chunk`

docling_core/types/doc/document.py
BREAKING CHANGE: export to text no longer escapes underscores.
Add `escaping_underscores` option to `export_to_markdown(). 
Set default value to `escaping_underscores` to True.
resolves #134
=> feat: add escaping_underscores option to markdown export

docling_core/types/doc/document.py
Add regex so that expressions that are enclosed between two dollar signs do not have their underscores modified. Extra code block is added to handle standalone equations export (adding `$$ equation $$`).
=> feat: escape underscores that are within latex equations

CHANGELOG.md
Change log refers to v3.16.0 but from context I think it is clear it means v2.16.0.
=> chore: Fix typo in CHANGELOG

docling_core/types/doc/document.py, docling_core/types/doc/tokens.py, docs/DoclingDocument.json
Clean up removing unnused tags at the moment, reliance mainly on DocItemLabel and DocumentTokens when unavoidable.
=> fix: Document Tokens (DocTag) clean up

docling_core/types/doc/document.py, test/data/doc/constructed_doc.embedded.md.gt, test/data/doc/constructed_doc.placeholder.md.gt, test/data/doc/constructed_doc.referenced.md.gt, test/data/doc/constructed_document.yaml.md
For now only covers basic ordered lists, i.e. starting from 1.
Special cases (different starting number, different symbols (e.g. latin) etc.) to be addressed separately as it may require minor reworking of the data model (e.g. adding some metadata to the GroupItem that represents an ordered list).
=> fix(markdown): fix handling of ordered lists

docling_core/transforms/chunker/hybrid_chunker.py, test/test_hybrid_chunker.py
`tokenize()` parameter `max_length` was previously set to `None`, but:
- as discussed in [DS4SD/docling#1072](https://github.com/DS4SD/docling/issues/1072), it's not recognized by all `PreTrainedTokenizerBase` implementations (e.g. `transformers.BioGptTokenizer.from_pretrained("microsoft/biogpt")`), and
- was anyway redundant, since (according to my understanding of the [tokenizer docs](https://huggingface.co/docs/transformers/en/main_classes/tokenizer)) `None` would anyway be the default
=> fix: remove `max_length` param from tokenization

.github/workflows/checks.yml
Porting https://github.com/DS4SD/docling/pull/1096 to docling-core as similar issues occur when using HuggingFace embedding models (e.g. for `HybridChunker` tests).
=> chore: use GH cache for HF models

docling_core/types/doc/document.py
https://github.com/DS4SD/docling-core/pull/166 newly routed cases for formulas with empty text and missing fallback into the try-except block resulting in excessive warning log entries. Those passed through the if-elif clause with only the logging side effect. Change it so that they bypass the clause without visiting the elif case, thus avoiding the logging.
=> fix: suppress warning for missing fallback case

docling_core/types/doc/document.py, docling_core/types/doc/tokens.py, test/data/doc/dummy_doc.yaml, test/data/doc/dummy_doc.yaml.dt
Add document tokens `<smiles>` and `</smiles>` for representing SMILES sequences. 
Example sequence:
`<smiles>CC1=CN2C=C(C3=NC(C)=NN3)N=C(CC3=CC=CC=C3F)C2=N1</smiles>`
=> feat: add document tokens for SMILES

docling_core/types/doc/document.py
Process page headers and footers as furniture
=> fix: DocTags support of furniture

docling_core/types/doc/document.py, docling_core/types/doc/page.py
This PR makes a minor change to the handling of the `filename` argument in the `save_as_*` and `load_from_*` methods of the `document` and `page` classes.
See: https://github.com/docling-project/docling/issues/1189
Currently, if a `str` is passed to the `save_as_*` or `load_from_*` methods of the `document` or `pages` types, it will fail with an `AttributeError`.
The changes in this PR handle `str` inputs to these methods, and automatically casts them to `pathlib.Path`.
I could add this to tests in `test_save_to_disk` in `test/test_docling.py`, but not sure the additional handling requires tests.
=> fix: add handling for str filenames in save/load methods

docling_core/types/doc/document.py
Value error, 'text/csv' is not a valid MIME type [type=value_error, input_value='text/csv', input_type=str]
For further information visit https://errors.pydantic.dev/2.10/v/value_error
converter = DocumentConverter()
result = converter.convert(Path("tests/data/csv/csv-comma.csv"))
output = result.document.export_to_markdown()
2.23.3
3.10.11
Windows 11
I have filed this PR in following to this issue [here](https://github.com/docling-project/docling/issues/1206).
=> fix: add 'text/csv' mimetype to _extra_mimetypes type list

docling_core/types/doc/page.py
Added automatic transformation of page cell_bbox coord origin to the same as input bbox.coord_origin when requesting get_cells_in_bbox.
Current behavior - is to throw error and stop if the input coord_origin differs from backend page coord_origin, which is almost always when get_cells_in_bbox is used in a client code of Docling. This PR fixes it, and presents resulting cells pre-transformed into the same origin as input crop bbox.
This small fix removes the overhead in the client code we put in Docling.
=> fix: Automatic transformation of output cells bbox coord origin defined by input in get_cells_in_bbox

docling_core/types/doc/base.py
Preventing intersection_over_self to throw DivisionByZero when area of the element is zero.
Should resolve this issue: https://github.com/docling-project/docling/issues/1266
=> fix: DivisionByZero in intersection_over_self

docling_core/types/doc/document.py, test/test_doctags_load.py
* Allow the list of images argument to `from_doctags_and_image_pairs` to be optional
* Verify that `load_from_doctags` works for `DocTagsDocument` without image
* Provide deserializer for `DocTagsDocument` from multipage DocTags with <page_break>
=> feat: allow images in doctags deserializer to be optional and support multipage

.github/codecov.yml, .github/workflows/cd.yml, .github/workflows/checks.yml, .github/workflows/ci.yml, .pre-commit-config.yaml, poetry.lock, pyproject.toml
This PR is enabling the coverage report.
Additionally, it enables tests which were not enabled in CI.
=> ci: add tests in ci with coverage upload

.github/codecov.yml, .github/workflows/checks.yml
- fix wrong argument in codecov
- fix indentation error in codecov yaml file
=> fix(codecov): fix codecov argument and yaml file

docling_core/types/doc/document.py
This matches pydantic's `model_dump` signature
=> chore: typehint DoclingDocument.export_to_dict return type

docling_core/types/doc/document.py
To fix `UnboundLocalError: cannot access local variable 'body_str' where it is not associated with a value` error in the edge case of an empty table.
=> fix: UnboundLocal variable

docling_core/types/doc/document.py, docling_core/utils/legacy.py
Since we don't rely on hashes for credentials and security, we should use the option `usedforsecurity=False` to facilitate FIPS use cases.
=> fix: hashlib usage for FIPS

docling_core/types/doc/document.py
Update for recovery in deserialization. Recover either:
- the existence of the item, or
- the existence + the location of the item,
in cases where the model enters infinite repetition during prediction.
If the end of the string is encountered instead of a closing tag, do not discard the item entirely. Instead, populate the `DoclingDocument` with available information.
=> fix: update deserialization for better recovery

docling_core/transforms/chunker/hybrid_chunker.py, docling_core/transforms/serializer/common.py, docling_core/types/doc/document.py, docs/DoclingDocument.json, poetry.lock, test/test_docling_doc.py, test/test_hybrid_chunker.py
It partially addresses https://github.com/docling-project/docling/issues/1557
- Update code to avoid deprecation warnings
- Catch and ignore deprecation warnings when we intentionally use deprecated fields
=> chore: fix deprecation warnings

docling_core/types/doc/document.py
Addresses issue where any tag from `<section_header_level_2>` up are lost in de-serialization.
=> fix: Support section_header levels in doctags deserialization

docling_core/types/doc/document.py
Resolves https://github.com/docling-project/docling/issues/1848
=> fix: add missing mimetypes for asr inputs

docling_core/types/doc/page.py, test/test_page.py
When in `CoordOrigin.TOPLEFT`, the computation of the `BoundingRectangle.angle` have to be adapted since the angle between the (x, y), axis is `3*pi / 2` and not `pi / 2`. 
If `BoundingRectangle.angle` describes the angle between (`r_0`, `r_1`) and the `x` axis, angle computation have to be adapted in the `CoordOrigin.TOPLEFT` case:
- fixed the `BoundingRectangle.angle`  computation in the case of the `CoordOrigin.TOPLEFT` case
=> fix: BoundingRectangle angle computation when in `CoordOrigin.TOPLEFT`

docling_core/types/doc/document.py, test/data/doc/constructed_doc.added_extracted_doc.json.gt, test/data/doc/constructed_doc.bulk_item_addition.json.gt, test/data/doc/constructed_doc.bulk_item_insertion.json.gt, test/data/doc/constructed_doc.deleted_items_range.json.gt, test/data/doc/constructed_doc.extracted_with_deletion.json.gt, test/data/doc/constructed_doc.inserted_extracted_doc.json.gt, test/data/doc/constructed_doc.inserted_items_with_insert_*.json.gt, test/data/doc/constructed_doc.inserted_list_items_with_insert_*.json.gt, test/data/doc/constructed_doc.manipulated_table.json.gt, test/test_docling_doc.py
A collection of methods for the DoclingDocument data type that enable the creation of more robust document editing tools in docling-mcp. Methods include:
- **Insert_\* methods**: similar to the add_* methods, except that they specify a sibling node rather than a parent node. They create the desired NodeItem and insert it into the document at the specified location (useful for non-sequential document generation/editing)
- **Range manipulation methods**: these methods allow NodeItems to be added/inserted/removed in groups, based either on a list of items, two start/end items, or a DoclingDocument. These methods can be useful in automated manipulation, but may also be useful in eventually allowing for parts of DoclingDocuments to be "re-converted" with different settings and then inserted …
=> feat: Additional DoclingDocument methods for use in MCP document manipulation

docling_core/types/doc/document.py, test/test_docling_doc.py
This PR is fixing two issues related to the creation of referenced images.
The management of input directory was only interpreting "non-absolute directories" relative to the current working directory.
It failed to work in the actual setup it was designed, i.e. the artifacts location relative to the target document output.
The logic saving the picture images relied on the old version, before the page images were introduced.
It failed when doing
- save a DoclingDocument with embedded images
- load the DoclingDocument
- save as markdown/html with referenced images
- no image was found and exported
Refs https://github.com/docling-project/docling-serve/issues/245
=> fix: referenced artifacts relative to the document location

docling_core/transforms/serializer/html.py
Nested `grid[i][j]` access in `HTMLTableSerializer.serialize` caused performance issues on large tables.
Replaced double indexing with row-level iteration (`for row in grid: for cell in row:`). Fixes #372
Removes repeated Pydantic lookups and improves serialization speed without changing output.
=> perf: cache grid property in HTMLTableSerializer

docling_core/transforms/serializer/html.py
HTMLTableSerializer Improvements
- Changed indexing to iteration for the 2D linked list grid due to performance issues with large XLSX exports to Markdown. The original implementation was extremely slow and wouldn't finish. It is good now.
- Also a tiny issue with text direction, and this PR fixes it.
fixes https://github.com/docling-project/docling-core/issues/279#issue-3033288664
=> fix: HTMLTableSerializer efficiency and dir attribute

docling_core/types/doc/document.py
This PR add a flag in the serialization of a `DoclingDocument` into markdown format to decide whether to escape reserved HTML characters (default) or not.
Resolves #387
=> fix: expose escape_html param to DoclingDocument md serialization

docling_core/types/doc/document.py
Moving log of deleting elements from info level to debug.
This is due to support of rich tables, while constructing them backends (docx, html) manipulate docling document tree, and sometimes need to delete elements, this creates excessive logging.
Note from the user: https://github.com/docling-project/docling/issues/2360#issuecomment-3372942862
=> chore: Silencing info logging on "delete_items" by moving it to debug level
